In [2]:
import numpy as np

In [3]:
array_1 = np.array([1,'v'])

In [4]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9,9]])

In [5]:
np.shape(arr3)

(3,)

In [21]:
import numpy as np
import pandas as pd
my_series = pd.Series([5, 6, 7, 8, 9, 10])
my_series.values



array([ 5,  6,  7,  8,  9, 10], dtype=int64)

In [26]:
a = np.ones((3,3,3))


In [33]:
np.random.randint(0, 5, 3)

array([2, 2, 0])

In [34]:
np.random.randint(0, 6, (3, 3))

array([[1, 0, 5],
       [2, 1, 3],
       [4, 3, 4]])

In [38]:
np.random.randint(0, 4, (3, 3))

array([[2, 1, 0],
       [2, 1, 1],
       [3, 0, 0]])

In [39]:
np.arange(1, 14, 2)

array([ 1,  3,  5,  7,  9, 11, 13])

In [40]:
np.array([i for i in range(11) if i%2])

array([1, 3, 5, 7, 9])

In [51]:
my_array = np.array([x for x in range(10) if x%3 == 0])

In [52]:
my_array

array([0, 3, 6, 9])

In [54]:
my_array = np.array([[1,2,3,4], [x for x in range(4)], [45,46,47,48]])
my_array[1][2]
my_array[1,2]

2

In [55]:
my_array[2,3]

48

In [199]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])

In [200]:
np.modf(big_secret)

(array([[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.6227766 , 0.65438358, 0.68595904, 0.71750305, 0.74901573,
         0.78049716, 0.81194744, 0.84336666, 0.8747549 , 0.90611227,
         0.93743885, 0.96873473, 0.        , 0.03123476, 0.06243908,
         0.09361307, 0.12475681, 0.15587038, 0.18695388, 0.21800739,
         0.2

In [198]:
column = 50
total = 0
for row in range(len(big_secret)):
    total += big_secret[row][column]
total

-1.0

In [196]:
total_2 = 1
for i in range(5):
    print(i)
    total_2 = total_2 * big_secret[i][46 + i]

0
1
2
3
4


In [197]:
total_2

-1.0

In [194]:
big_secret[::2,::2] = -1
big_secret[::3,::3] = 1

big_secret

# Python 9.4

In [205]:
number = [x for x in range(1,11)]

In [206]:
number

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [228]:
height_list = '135 160 163 147 138 149 136 154 137 165'.split()
map_object = map(int, height_list)
height = list(map_object)
height

[135, 160, 163, 147, 138, 149, 136, 154, 137, 165]

In [229]:
weight_list = '34 43 40 44 41 54 39 48 35 60'.split()
map_object = map(int, weight_list)
weight = list(map_object)
weight

[34, 43, 40, 44, 41, 54, 39, 48, 35, 60]

In [232]:
avg_score = '4 5 4.3 5 4.7 3.9 4.2 4.9 3.7 4.6'.split()
map_object = map(float, avg_score)
avg_score = list(map_object)
avg_score

[4.0, 5.0, 4.3, 5.0, 4.7, 3.9, 4.2, 4.9, 3.7, 4.6]

In [237]:
students = np.array([number, height, weight, avg_score])

In [252]:
students = students.T

In [253]:
mean = np.mean(students[:,-1])

In [254]:
mean

4.430000000000001

In [261]:
median = np.median(students[:,-2])
mean = np.mean(students [:,-2])
round(mean - median,1)

1.8

In [271]:
a = np.corrcoef(students[:,1],students[:,-2])
b = np.corrcoef(students[:,1], students[:,-1])
c = np.corrcoef(students[:,2], students[:,-1])
print(a)
print(b)
print(c)

[[1.         0.64314431]
 [0.64314431 1.        ]]
[[1.         0.46293714]
 [0.46293714 1.        ]]
[[1.         0.29801325]
 [0.29801325 1.        ]]


In [273]:
d = np.std(students[:,-1])
d

0.4517742799230607

In [277]:
f = np.std(students[:,-2])

In [281]:
f**2

60.36

# Final test

In [6]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])

In [7]:
my_array_2 = my_array[1:4,1:4]

In [8]:
my_array_2

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [16]:
np.shape(my_sin)

(5, 5)

In [70]:
my_sin = np.sin(my_array)

In [71]:
a = np.sum(my_sin)
round(a,3)

-0.058

In [72]:
my_sin[1:4, 1:4] = 1

In [73]:
my_sin

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  1.        ,  1.        ,  1.        , -0.54402111],
       [-0.99999021,  1.        ,  1.        ,  1.        ,  0.65028784],
       [-0.28790332,  1.        ,  1.        ,  1.        ,  0.91294525],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175]])

In [74]:
np.sum(my_sin)

7.571718421269144

In [87]:
my_sin_reshape = my_sin[::,:4].reshape(10,2)

In [88]:
my_sin_reshape

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.2794155 ,  1.        ],
       [ 1.        ,  1.        ],
       [-0.99999021,  1.        ],
       [ 1.        ,  1.        ],
       [-0.28790332,  1.        ],
       [ 1.        ,  1.        ],
       [ 0.83665564, -0.00885131],
       [-0.8462204 , -0.90557836]])

In [82]:
my_sin[::,0:4]

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.2794155 ,  1.        ,  1.        ,  1.        ],
       [-0.99999021,  1.        ,  1.        ,  1.        ],
       [-0.28790332,  1.        ,  1.        ,  1.        ],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836]])

In [89]:
np.shape(my_sin_reshape)

(10, 2)

In [92]:
total = 0
for i in range (10):
    total += my_sin_reshape[i][0]
round(total,3)

2.406

In [91]:
total

2.4057172058139544

In [121]:
num_list = []
for num in range (101,1001,2):
    num_list.append(num**2)
bigdata = np.array(num_list)
bigdata

array([ 10201,  10609,  11025,  11449,  11881,  12321,  12769,  13225,
        13689,  14161,  14641,  15129,  15625,  16129,  16641,  17161,
        17689,  18225,  18769,  19321,  19881,  20449,  21025,  21609,
        22201,  22801,  23409,  24025,  24649,  25281,  25921,  26569,
        27225,  27889,  28561,  29241,  29929,  30625,  31329,  32041,
        32761,  33489,  34225,  34969,  35721,  36481,  37249,  38025,
        38809,  39601,  40401,  41209,  42025,  42849,  43681,  44521,
        45369,  46225,  47089,  47961,  48841,  49729,  50625,  51529,
        52441,  53361,  54289,  55225,  56169,  57121,  58081,  59049,
        60025,  61009,  62001,  63001,  64009,  65025,  66049,  67081,
        68121,  69169,  70225,  71289,  72361,  73441,  74529,  75625,
        76729,  77841,  78961,  80089,  81225,  82369,  83521,  84681,
        85849,  87025,  88209,  89401,  90601,  91809,  93025,  94249,
        95481,  96721,  97969,  99225, 100489, 101761, 103041, 104329,
      

In [123]:
median = np.median(bigdata[::])

In [124]:
median

302501.0

In [125]:
std = np.std(bigdata)

In [126]:
round(std)

292095.0

In [140]:
a = bigdata.reshape(225,2)
a = a.T

In [142]:
corr = np.corrcoef(a[:,0],a[:,1])

In [143]:
corr

array([[1., 1.],
       [1., 1.]])

In [141]:
a.shape

(2, 225)